import_file
import_file_OpenMP
close('all')
B=cell2mat(B);
B=str2double(B);
C=A(2:end,1);
T=reshape(C,A(1),B);
Tn1=flip(T);
figure
contourf(fliplr(Tn1))

B_MP=cell2mat(B_MP);
B_MP=str2double(B_MP);
C_MP=A_MP(2:end,1);
T_MP=reshape(C_MP,A_MP(1),B_MP);
Tn1_MP=flip(T_MP);
figure
contourf(Tn1_MP)
figure
contourf(Tn1-Tn1_MP)
%l2_norm_Tn=sum(sum(sqrt(Tn1^2-Tn1_MP^2)));